### ISSUE TITLE
大佬,8.13.0是不是不能破

### ISSUE THREAD

**Issue by shenmadouyaowen** [wolfbolin/crack-elasticsearch-by-docker#11]
大佬,8.13.0是不是不能破

**Comment by wolfbolin** [comment]
应该是可以的，只是版本升级太快，又是最新的版本，所以没有验证。

**Comment by shenmadouyaowen** [comment]
> 应该是可以的，只是版本升级太快，又是最新的版本，所以没有验证。

我刚刚试了一下,认证模板用的是你的platinum_license.json,报以下错误:
![image](https://github.com/wolfbolin/crack-elasticsearch-by-docker/assets/12426724/f4afa88b-e2ba-400b-9b45-7c511ad14516)

**Comment by wolfbolin** [comment]
那个platinum_license.json是验证过的，你的这个报错要考虑是不是没有把重新编译好的jar放在**正确的路径**和使用**正确的名字**。
如果版本不兼容，理论上编译jar和es启动过程是会出错的。

**Comment by shenmadouyaowen** [comment]
是的理论上是会报错,但是我放上去了依旧提示上面错误,重启了docker也是这样
![image](https://github.com/wolfbolin/crack-elasticsearch-by-docker/assets/12426724/0280c8ae-9034-4f0a-a3f7-165c54e2dcc5)
把下面红色框框的f复制过去改名替换,应该没错吧
![image](https://github.com/wolfbolin/crack-elasticsearch-by-docker/assets/12426724/9c739a83-0ea2-4ae5-8406-ad6e2aa1619b)

**Comment by shenmadouyaowen** [comment]
我在另外一台电脑使用了sudo ./crack_and_install.sh $version也不行, 8.12.1 版本的

**Comment by shenmadouyaowen** [comment]
是可以,我自己动了platinum_license.json 文件
![image](https://github.com/wolfbolin/crack-elasticsearch-by-docker/assets/12426724/6d8c108a-63a1-4f10-bff2-b01ad6585659)
