### ISSUE TITLE
7.17.2 运行错误 

### ISSUE THREAD

**Issue by molixiaoge** [wolfbolin/crack-elasticsearch-by-docker#13]
![图片](https://github.com/user-attachments/assets/c93e6d8a-aae7-4372-b78e-823986965696)

**Comment by wolfbolin** [comment]
可以尝试使用最新版的master再试一下，已经根据7.x版本进行了修改。目前可通过编译。

**Comment by molixiaoge** [comment]
试了一下 7.17.2 和7.17.20 都可以编译通过了
