### ISSUE TITLE
请问可以修改为企业级的订阅吗？

### ISSUE THREAD

**Issue by fhisrq** [wolfbolin/crack-elasticsearch-by-docker#14]
https://www.elastic.co/cn/pricing
有些功能需要企业级才支持，但是我尝试修改成type:enterprise，kibana就登录不上了，日志报错：
![image](https://github.com/user-attachments/assets/a0988e41-c9ef-486f-bd37-70fe9d2bae48)

**Comment by fhisrq** [comment]
elasticsearch使用api查询_license，可以看到企业订阅已经生效

**Comment by wolfbolin** [comment]
导入证书时没有遇到如下报错吗？
```
Error encountered uploading license: license type [enterprise] is not a valid for version [3] licenses
```

**Comment by wolfbolin** [comment]
代码修改 426c7b29118db0016feed39764c2925bc7ed98e9

修改前无法导入企业级证书。目前可以尝试最新的master分支来允许证书导入，改动后测试企业级证书可导入、kibana可用。

**Comment by wolfbolin** [comment]
![image](https://github.com/user-attachments/assets/e734bd19-4c83-4fc5-bd4d-e9401220ddb0)

**Comment by fhisrq** [comment]
我找到问题了，
![image](https://github.com/user-attachments/assets/c88ca79d-eacb-4db7-bf44-8f7631e5ec03)
您的Enterprise许可证不支持 security。请升级您的许可证。
Your Enterprise license does not support security. Please upgrade your license.
我有在用elastic security，白金授权的时候默认json就可以了，我怀疑企业版的license json需要添加多一些什么

**Comment by fhisrq** [comment]
> 导入证书时没有遇到如下报错吗？
> 
> ```
> Error encountered uploading license: license type [enterprise] is not a valid for version [3] licenses
> ```

这里我用了"type":"Enterprise"，大写E

**Comment by fhisrq** [comment]
我的版本号是8.14.3，安装方式采用本地apt安装，然后复制x-pack-core-8.14.3.crack.jar到本地

**Comment by wolfbolin** [comment]
https://github.com/elastic/elasticsearch/blob/168b910c0aa2ea2c6c62783f78b19a731e7e94b7/x-pack/plugin/core/src/main/java/org/elasticsearch/license/License.java#L89-L103

理论上来说应该只有小写的可以，不知道你的大写E是怎么混过去的。建议你用最新的master重新编一个jar替换进去，然后重新导入一个enterprise的证书来刷新一下。

**Comment by fhisrq** [comment]
诶，我改成小写的就完全正常了，在你的上一个版本是因为小写e过不去，尝试了一下大写E就导入成功了（但不能登录），谢谢你，此issue可以结束了

**Comment by 905839698** [comment]
你没有遇到许可证自动丢失的情况吗？我是可以导入成功，但是会自动丢失，时间不定
