### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 905839698** [wolfbolin/crack-elasticsearch-by-docker#16]
Registering [platinum] licenses is not allowed on this cluster
![image](https://github.com/user-attachments/assets/de37bb45-d0f3-4ee5-8906-fa3bff2b8a11)

**Comment by 905839698** [comment]
修改"type": "enterprise"处理了，但是会出现许可证丢失的问题，不稳定

**Comment by wolfbolin** [comment]
建议使用“platinum”，企业版无法验证和保障稳定性。企业版的证书代码检查会更多一点，破解脚本里也许会有遗漏的部分。可以直接使用代码仓里的证书导入验证。
