### ISSUE TITLE
获取8.4.3版本的报错…

### ISSUE THREAD

**Issue by orwithout** [wolfbolin/crack-elasticsearch-by-docker#2]
![Uploading Snipaste_2022-11-07_14-36-12.png…]()

**Comment by orwithout** [comment]
rocky linux 8 系统


[root@ttt crack-elasticsearch-by-docker]# systemctl enable docker
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /usr/lib/systemd/system/docker.service.
[root@ttt crack-elasticsearch-by-docker]# bash crack.sh $version
Run for version: 8.4.3
Error response from daemon: No such container: elastic-crack
Error: No such container: elastic-crack
Sending build context to Docker daemon  66.56kB
Step 1/13 : ARG VERSION
Step 2/13 : FROM elasticsearch:${VERSION} AS Baseline
8.4.3: Pulling from library/elasticsearch
675920708c8b: Pull complete
ad25a8ce517d: Pull complete
44bc58111791: Pull complete
c030cb8b3c40: Pull complete
ce4bbb7bdb12: Pull complete
7061d37f045f: Pull complete
4c204de0d071: Pull complete
d43dd3e01e67: Pull complete
828c381bc69a: Pull complete
Digest: sha256:bb72a5788e156171b111d2fc21825d007f235c3314295aa86d0ef500678923bd
Status: Downloaded newer image for elasticsearch:8.4.3
 ---> ce2b9dc7fe85
Step 3/13 : FROM openjdk:17-jdk-buster
17-jdk-buster: Pulling from library/openjdk
85bed84afb9a: Pull complete
5fdd409f4b2b: Pull complete
fa3069e6cecf: Pull complete
4ee16f45eff9: Pull complete
d8a4f10afb0a: Pull complete
7106c9fc6ffa: Pull complete
Digest: sha256:fcc1f2be2f2361da9a9f65754864218fe5fed86ea085ca39779114c91edfd41a
Status: Downloaded newer image for openjdk:17-jdk-buster
 ---> 629cbc2df164
Step 4/13 : ARG VERSION
 ---> Running in 7e9ebce78578
Removing intermediate container 7e9ebce78578
 ---> ab30c8c8c4ce
Step 5/13 : ARG HTTP_PROXY
 ---> Running in 13d598e94451
Removing intermediate container 13d598e94451
 ---> 38dd24e103b2
Step 6/13 : ARG HTTPS_PROXY
 ---> Running in 1e76ee9a734b
Removing intermediate container 1e76ee9a734b
 ---> bc7bb1eac4c0
Step 7/13 : ENV VERSION=${VERSION}
 ---> Running in 61d085ee9d27
Removing intermediate container 61d085ee9d27
 ---> 3c03a5be48e2
Step 8/13 : WORKDIR /crack
 ---> Running in bf66cea4f423
Removing intermediate container bf66cea4f423
 ---> 19e7b6dcb016
Step 9/13 : COPY --from=Baseline /usr/share/elasticsearch/lib /usr/share/elasticsearch/lib
 ---> dc6e682f00e6
Step 10/13 : COPY --from=Baseline /usr/share/elasticsearch/modules/x-pack-core /usr/share/elasticsearch/modules/x-pack-core
 ---> b16047c8118a
Step 11/13 : COPY build_crack_jar.sh /crack
 ---> 756da95f09ae
Step 12/13 : RUN apt update && apt install -y zip
 ---> Running in e5f9849b7a84

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Err:1 http://security.debian.org/debian-security buster/updates InRelease
  Connection failed [IP: 151.101.78.132 80]
Err:2 http://deb.debian.org/debian buster InRelease
  Connection failed [IP: 151.101.78.132 80]

Err:3 http://deb.debian.org/debian buster-updates InRelease
  Connection failed [IP: 151.101.78.132 80]
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Connection failed [IP: 151.101.78.132 80]
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Connection failed [IP: 151.101.78.132 80]
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Connection failed [IP: 151.101.78.132 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Package zip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'zip' has no installation candidate
The command '/bin/sh -c apt update && apt install -y zip' returned a non-zero code: 100
Unable to find image 'elastic-crack:8.4.3' locally
docker: Error response from daemon: pull access denied for elastic-crack, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
[root@ttt crack-elasticsearch-by-docker]#
[root@ttt crack-elasticsearch-by-docker]# ll
total 16
-rwxr-xr-x 1 root root 1745 Nov  7 14:23 build_crack_jar.sh
-rwxr-xr-x 1 root root  438 Nov  7 14:23 crack.sh
-rw-r--r-- 1 root root  463 Nov  7 14:23 Dockerfile
-rw-r--r-- 1 root root 1189 Nov  7 14:23 README.md
[root@ttt crack-elasticsearch-by-docker]#
![Snipaste_2022-11-07_14-36-12](https://user-images.githubusercontent.com/19142891/200242324-d12f3632-3239-42b8-b500-f1bf859b56a0.png)

**Comment by fuomag9** [comment]
you have either connection issues or the mirrors were not working

**Comment by Nurlan199206** [comment]
not working on 8.4.3, i'm copying generated jar to folder

**Comment by wolfbolin** [comment]
Debian源裸连失败，参考Readme挂上代理后执行。
