### ISSUE TITLE
8.8.1ES 成功

### ISSUE THREAD

**Issue by knifecaojia** [wolfbolin/crack-elasticsearch-by-docker#6]
8.8.1成功激活并开启X-PACK

**Comment by Sirius2016** [comment]
> 8.8.1成功激活并开启X-PACK

你好，请问是如何激活的，我激活时提示：

**Comment by Sirius2016** [comment]
> 8.8.1成功激活并开启X-PACK
我激活失败，请问你是如何激活的。@knifecaojia @wolfbolin
Error encountered uploading license: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "src" is null"

**Comment by wolfbolin** [comment]
恭喜成功，我将直接尝试更高级别的版本。
